use biblioteca;
go

create table usuario(
idUsuario  int primary key identity(1,1),
nombre varchar(80),
direccion varchar(200)
);

create table genero(
idGenero int primary key identity(1,1),
nombre	varchar(50),
descripcion varchar(2000)
);

create table libro(
idLibro	 int primary key identity(1,1),
titulo	varchar(100),
autor	varchar(100),
idGenero	int,
idioma	varchar(20),
resumen	varchar(2000),
constraint FkLibroGenero
	foreign key (idGenero) references genero(idGenero)
);

create table ejemplar(
idEjemplar  int primary key identity(1,1),
idLibro	int,
idUsuario int default null,
constraint FkEjemplarLibro
	foreign key (idLibro) references libro(idLibro),
constraint FkEjemplarUsuario
	foreign key (idUsuario) references usuario(idUsuario)
);

insert into genero values
('Sátira','La sátira es un género literario que expresa indignación hacia alguien o algo, con propósito moralizador, lúdico o meramente burlesco. Se puede escribir en prosa, verso o alternando ambas formas (sátira menipea). Se inspira en la poesía yámbica griega y se desarrolló sobre todo en la literatura latina.'),
('Cuento','Un cuento (del latín, compŭtus, cuenta)​ es una narración breve creada por uno o varios autores, puede ser basada ya sea en hechos reales como ficticios, cuya trama es protagonizada por un grupo reducido de personajes y con un argumento relativamente sencillo.'),
('Novela','La novela (del italiano novella) es una obra literaria en la que se narra una acción fingida en todo o en parte y cuyo fin es causar placer estético a los lectores con la descripción o pintura de sucesos o lances interesantes así como de personajes, pasiones y costumbres, que en muchos casos sirven de insumos para la propia reflexión o introspección.'),
('Poema épico','La épica (del adjetivo: ἐπικός, epikós; de ἔπος, épos palabra, historia, poema)​es un género narrativo en el que se presentan hechos legendarios o ficticios relativos a las hazañas de uno o más héroes y a las luchas reales o imaginarias en las que han participado estos héroes ya sean inventados o de sueños'),
('Cantar de gesta','Cantar de gesta es el nombre dado a la epopeya escrita en la Edad Media o a una manifestación literaria extensa perteneciente a la épica que narra las hazañas de un héroe cuyas virtudes representan modelos para un pueblo o colectividad durante el Medievo.'),
('Romance','El término romance (del inglés, romance) o román (del francés roman) suele utilizarse, en la actual teoría de la literatura, para hacer referencia a un relato extenso de ficción, normalmente en prosa, que se diferencia de la novela moderna porque presenta un mundo imaginario en el que los personajes y situaciones pertenecen a la esfera de lo maravilloso y lo insólito.'),
('Comedia','La comedia (del latín comoedĭa, y este del griego antiguo κωμῳδία, kōmōidía)​ es el género dramático opuesto a la tragedia​ y, por lo tanto, relacionado casi siempre con historias con final feliz.'),
('Drama','El término drama proviene del idioma griego y significa “hacer” o “actuar”. Se divide en géneros realistas y géneros no realistas; entre los primeros, se inscriben (desde los orígenes) la tragedia y la comedia, y más tarde se agregan otras modalidades como obra didáctica y la tragicomedia (también conocida como comedia trágica clásica), mismas que empiezan a generarse desde el Renacimiento. '),
('Tragedia','La tragedia es una forma literaria, teatral o dramática del lenguaje solemne, cuyos personajes protagónicos son ilustres y se ven enfrentados de manera misteriosa, invencible e inevitable, a causa de un error fatal o condición de carácter (la llamada hamartia) contra un destino fatal (fatum, hado o sino) o los dioses, generando un conflicto cuyo final es irremediablemente triste: la destrucción del héroe protagonista, quien muere o enloquece.'),
('Historia','La historia es la ciencia que tiene como objetivo el estudio de sucesos del pasado, tradicionalmente de la humanidad​, y como método, el propio de las ciencias sociales/humanas, así como el de las ciencias naturales en un marco de interdisciplinariedad.'),
('Novela histórica','La novela histórica es un subgénero narrativo que se configuró en el Romanticismo del siglo XIX y que ha continuado desarrollándose con bastante éxito en los siglos XX y XXI. Utilizando un argumento de ficción, como cualquier novela, tiene la característica de que este se sitúa en un momento histórico concreto y los acontecimientos históricos reales suelen tener cierta relevancia en el desarrollo del argumento.'),
('Viajes','La literatura de viajes es un subgénero literario que incluye textos que recogen los acontecimientos, sentimientos e impresiones de un viajero'),
('Novela policíaca','La novela policíaca, policiaca, policial, detectivesca o, con más amplitud y precisión, la novela criminal, es una clase de textos o género literario dentro de la novela, que es a su vez un subgénero de la narrativa.');

insert into libro values
('Rinconete y Cortadillo', 'Miguel de Cervantes', 3, 'Español', 'En la Venta del Molinillo, en el camino de Toledo a Andalucía, se encuentran dos muchachos que han escapado de sus casas. Después de resaltarse su aspecto desharrapado y de que ambos golfillos se cuenten brevemente sus vidas en un ingenioso diálogo, Pedro de Rincón y Diego Cortado, asociados ya en la golfería, despluman a un arriero jugando a las cartas. Seguidamente, en compañía de unos viajeros emprenden la marcha hacia Sevilla, en donde se estrenan como mozos portadores de mercancías. Cortado roba una bolsa de dinero a un sacristán que se le acerca y al que engaña. Pero otro mozo que había observado el latrocinio advierte a ambos muchachos que allí no se puede robar por libre: tienen que presentarse en la cofradía de Monipodio para su registro en el hampa sevillana. Rincón y Cortado visitan la casa del maestro de la golfería- por el camino se enteran de algunos usos y costumbres de tan "devota" organización, a la vez que son espectadores de aquel asombroso mundo extrasocial de ladrones, golfos, delincuentes, rufianes, valentones y coimas, que, dirigidos por Monipodio, constituyen la flor y nata del hampa sevillana, consentida y aún fomentada por una sociedad corrompida'),
('Much Ado About Nothing', 'William Shakespeare', 7, 'Inglés', 'Benedick and Beatrice are tricked into confessing their love for each other, and Claudio is tricked into believing that Hero is not a maiden (virgin). Claudio therefore rejects Hero at the altar. However, Hero is vindicated, and marriages are arranged for both pairs.'),
('La vida es sueño', ' Pedro Calderón de la Barca', 8, 'Español', 'La vida es sueño es una obra de teatro de Pedro Calderón de la Barca estrenada en 1635 y perteneciente al movimiento literario del barroco. El tema central es la libertad del ser humano para configurar su vida, sin dejarse llevar por un supuesto destino.'),
('La tragedia de Hamlet', 'William Shakespeare', 9, 'Español', 'La obra transcurre en Dinamarca, y trata de los acontecimientos posteriores al asesinato del rey Hamlet (padre del príncipe Hamlet), a manos de su hermano Claudio. El fantasma del rey pide a su hijo que se vengue de su asesino.La obra discurre vívidamente alrededor de la locura (tanto real como fingida), y de la transformación del profundo dolor en desmesurada ira. Además de explorar temas como la traición, la venganza, el incesto y la corrupción moral.'),
('Fausto', 'Johann Wolfgang von Goethe', 9, 'Español', 'Casi doscientos cincuenta años después del nacimiento de su autor, "Fausto" sigue siendo un clásico, pues plantea el problema de los límites y el sentido de la acción humana, y lo hace bajo la parábola del pacto con el diablo. La obra mantiene su vigencia hoy porque, mediante los interrogantes propios de la condición humana, reaviva la inquietud en una época que pretende sentirse ajena a ellos. En realidad, "Fausto "reúne dos obras distintas enmarcadas en momentos muy concretos de la historia europea: el posterior a la Revolución Francesa y el de la consiguiente Restauración monárquica. En el drama se citan, igualmente, dos perfiles muy distintos de Goethe (Frankfurt, 1749 - Weimar, 1832): el alma de un joven lleno de desasosiego y la atemperada vejez de un funcionario jubilado. Si a lo largo de sesenta y cuatro años de creación varía el autor, también cambia su personaje. En la primera parte, un triste erudito se lanza a una desesperada acumulación de experiencias. En la segunda, un hombre lúcido cifra su máxima esperanza en crear un pueblo libre en una tierra libre. Una pretenciosa individualidad es sacrificada en aras de una utopía comunitaria por la que siempre merezca la pena luchar.'),
('L’ Avare', 'Molière', 7, 'Francés', 'L’Avare est une comédie de Molière en cinq actes et en prose, adaptée de La Marmite (Aulularia) de Plaute et représentée pour la première fois sur la scène du Palais-Royal le 9 septembre 1668. Il s’agit d’une comédie de caractère dont le personnage principal, Harpagon, est caractérisé par son avarice caricaturale. Harpagon tente de marier sa fille de force, tout en protégeant obstinément une cassette pleine d’or. Les cinq actes comportent respectivement cinq, cinq, neuf, sept, et six scènes'),
('Decamerón', 'Giovanni Boccaccio', 2, 'Español', 'El Decamerón empieza con un breve proemio,​ preámbulo en el que el autor habla en nombre propio. Por cuestiones de amor decide consagrar un poco de su tiempo a los placeres de un público lector principalmente femenino.La primera jornada viene precedida de una descripción de la peste y del relato de cómo se produjo el encuentro fortuito de los narradores de estas historias. El Decamerón contiene así una descripción de los efectos físicos, psicológicos y sociales que la peste bubónica ejerció en esa parte de Europa.'),
('Veinte mil leguas de viaje submarino', 'Julio Verne', 3, 'Español', 'La historia comienza con una expedición a bordo de un buque de la marina de guerra estadounidense: el Abraham Lincoln, al mando del almirante Farragut, que busca dar caza a un extraño cetáceo, con un largo y filoso cuerno en el hocico (luego se demuestra que el animal es un narval), que había ocasionado daños a diversas embarcaciones. Durante la expedición, los protagonistas se ven lanzados por la borda del buque como resultado de una embestida del animal. El profesor Aronnax y su acompañante Conseil son rescatados por el arponero canadiense Ned Land que también cayó al agua con ellos, después del impacto de la criatura, y los tres logran llegar a nado a un lugar seguro. Una vez a salvo, descubren que no se encuentran realmente en una isla, sino sobre una estructura metálica: un submarino a flote a cuyo interior acceden por una compuerta, llevados por ocho enmascarados.'),
('Guerra y paz', 'León Tolstói', 11, 'Español', 'La trama se desarrolla fundamentalmente durante la invasión napoleónica de Rusia siguiendo la historia entrelazada de cuatro familias'),
('Tres tristes tigres', 'Guillermo Cabrera Infante', 3, 'Español', 'Una recreación nostálgica de La Habana de 1958, y en especial de su vida nocturna.'),
('Pantaleón y las visitadoras', 'Mario Vargas Llosa', 3, 'Español', 'La historia se desarrolla en la Amazonía Peruana, donde los efectivos del Ejército del Perú son atendidos por un servicio de prostitutas, a quienes llaman "visitadoras". Según el propio autor, la obra se basa en hechos reales, según él mismo pudo constatarlo en 1958 y 1964, cuando viajó a la selva del Perú.'),
('Ficciones', 'Jorge Luis Borges', 2, 'Español', 'Compuesto de dos partes: El jardín de senderos que se bifurcan y Artificios. su publicación en 1944 colocó a Borges en un primer plano de la literatura universal. Fue incluida en la lista de las 100 mejores novelas en español del siglo XX del periódico español «El Mundo», así como también en la lista de los 100 libros del siglo XX del diario francés Le Monde y en los 100 mejores libros de todos los tiempos del Club de libros de Noruega.'),
('Bestiario', 'Julio Cortazar', 2, 'Español', 'Es el primer libro de relatos que Julio Cortázar publicó con su auténtico nombre. Estas ocho obras maestras: son perfectas. Estos cuentos, que hablan de objetos y hechos cotidianos, pasan a la dimensión de la pesadilla o de la revelación de un modo natural e imperceptible.'),
('Una Historia de España', 'Arturo Pérez-Reverte', 1, 'Español', 'Un relato ácido, divertido, personal y poco ortodoxo de Arturo Pérez-Reverte sobre la historia de España'),
('After Dark', 'Haruki Murakami', 3, 'Español', 'Eri y Mari son hermanas que se diferencian en algo más que en una sílaba de su nombre. Eri, la mayor, es una belleza que trabaja de modelo. Mari, más poca cosa, es introvertida y buena estudiante. Y entre las dos ha crecido una distancia inabarcable.​Cerca de medianoche, Mari Asai, una chica de 19 años toma un café en un restaurante mientras lee. La noche es larga y no quiere pasarla en su casa. En este lugar se encuentra con Takahashi, estudiante y viejo compañero de su hermana, quien ensaya esa noche con su banda en un local cercano. Mientras, en una habitación, Eri Asai se ha sumido en una dulce inconsciencia; el televisor cobra vida y empieza a distinguirse en la pantalla una imagen perturbadora. Lo más inquietante: el televisor no está enchufado. Entrada la noche, la encargada de un love-hotel pide a Mari que la ayude con una prostituta china que ha sido agredida en una de las habitaciones. Conversando con estos dos personajes Mari descubre que la única manera de ayudar a su hermana está en sus manos'),
('The Caves of Steel', ' Isaac Asimov', 13, 'Inglés', 'In this novel, Isaac Asimov introduces Elijah Baley and R. Daneel Olivaw, later his favorite protagonists. They live roughly three millennia in Earth’s future, a time when hyperspace travel has been discovered, and a few worlds relatively close to Earth have been colonized — fifty planets known as the "Spacer worlds". The Spacer worlds are rich, have low population density (average population of one hundred million each), and use robot labor heavily. Meanwhile, Earth is overpopulated (with a total population of eight billion, three times that of Asimov’s 1950s) and strict rules against robots have been passed. In The Caves of Steel and its sequels (the first of which is The Naked Sun), Asimov paints a grim situation of an Earth dealing with an extremely large population, and of luxury-seeking Spacers, who limit birth to permit great wealth and privacy.'),
('Las damas de oriente', 'Cristina Morató', 10, 'Español', 'Este libro recoge las apasionantes vidas de unas mujeres atraídas por el mundo árabe que dejaron su huella en Oriente Próximo: lady Mary Montagu, la primera occidental en acceder al interior de los harenes otomanos, la excéntrica lady Hester Stanhope, la hermosa lady Jane Digby, que vivióuna apasionada historia de amor con un jefe beduino o, ya entrado el siglo XX, otras audaces exploradoras, arqueólogas y espías al servicio del Imperio Británico como Gertrude Bell, que en calidad de secretaria para Oriente ayudó a trazar las fronteras del actual Irak, la incansable Freya Stark y la famosa escritora de novelas policíacas Agatha Christie.'),
('La balsa de piedra', 'José Saramago', 3, 'Español', 'Cuenta la historia ficticia de la separación geográfica de la península ibérica del resto del continente europeo. Ha sido traducida a más de veinte idiomas y adaptada al cine.'),
('El médico', 'Noah Gordon ', 11, 'Español', 'La novela trata sobre la vida de Rob J. Cole, hijo de una familia del gremio de carpinteros de Londres, que a los nueve años queda huérfano y sin hogar. La muerte de sus padres le descubre su «don» de percibir si alguien está próximo a la muerte solo con tocarlo. Durante unos días se encarga del cuidado de sus dos hermanos, a quienes el jefe del gremio va encontrando nuevos hogares. Cuando se queda solo, bajo el peligro de ser vendido como esclavo, fortuitamente pasa a ser el ayudante-aprendiz de Henry Croft (Barber), un hombre campechano que recorre Inglaterra montando espectáculos de malabarismo para atraer público a su negocio de cirujano-barbero, donde realiza pequeñas curas y vende un brebaje curalotodo: la «Panacea Universal». Los viajes que realizarán en los siguientes años dan a Rob la esperanza de reencontrarse con sus hermanos pequeños, pero su búsqueda resulta infructuosa. Durante años comparten cartel y, tras terminar Rob su periodo de aprendiz, llegarán a repartirse los beneficios de los espectáculos, hasta que repentinamente Barber muere de un ataque al corazón'),
('El ocho', 'Katherine Neville', 11, 'Español', 'El libro cuenta la historia del ajedrez de Montglane y el ansia de ciertas personas por conseguirlo a lo largo de la historia. Por un lado encontramos a las novicias de la abadía de Montglane: Valentine y Mireille. Ellas, al cierre de la abadía, deberán irse (con varias piezas del ajedrez) con el padrino de una de ellas, Jacques-Louis David. El pintor les presentará a Charles Maurice de Talleyrand-Périgord, quién también conoce la historia del ajedrez. Todo esto en el contexto de la Revolución francesa; personajes históricos como Marat, Robespierre o Catalina la Grande aparecen en esta parte de la historia para ayudar a encontrar (o conseguir) el ajedrez de Montglane.')

